server:
  port: ${SERVER_PORT}



spring:
  config:
    import: optional:file:.env[.properties]
  profiles:
    include: mq-${MESSAGE_QUEUE_TYPE},cache-${CACHE_TYPE},store-${STORE_TYPE}
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: /mapper/sqlite/**/*.xml


security:
  ignores:
    - /account
    - /test/ignore
    - /error
    - /actuator/*
    - /actuator
idempotent:
  urls:
    - /test/idempotent
    - /game/archive/file