spring:
  liquibase:
    change-log: changelog-master-mysql.xml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/game_archive_manager
    username: root
    password: 123456


store:
  type: mysql